# Server configuration
server:
  port: 9050

api:
    host: test.jc519.com:9010/api/search

# Spring configuration
spring:
  #应用(服务)名称
  application:
    name: jc-search-microservice
  datasource.jc:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp13dz4j5kb15k6d0to.mysql.rds.aliyuncs.com:3306/jc519?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=true
    username: jc_write_01
    password: HyfzWrite!@#qwe893
  jackson:
    time-zone:  GMT+8

  # REDIS (RedisProperties)
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 172.16.240.218
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 9uskwSY2NgQsMcse
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0

  #solr配置
  data.solr:
    host: http://172.16.240.218:8983/solr
    collection:
      noControlMedicineGoods: ${spring.data.solr.host}/noControlMedicineGoods
      controlMedicineGoods: ${spring.data.solr.host}/controlMedicineGoods
      hotWords: ${spring.data.solr.host}/hotWords

#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.240.218:8761/eureka/

# Logging configuration
logging:
  level:
    org.springframework:
      cloud: DEBUG
    com.jc519: DEBUG