# Server configuration
server:
  port: 9050

api:
    host: localhost:9050

# Spring configuration
spring:
  #应用(服务)名称
  application:
    name: jc-search-microservice
  datasource.jc:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp13dz4j5kb15k6d0to.mysql.rds.aliyuncs.com:3306/jc519?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=true
    username: jc_write_01
    password: HyfzWrite!@#qwe893
  jackson:
    time-zone:  GMT+8

  #solr配置
  data.solr:
    host: http://101.37.147.193:8983/solr
    collection:
      noControlMedicineGoods: ${spring.data.solr.host}/noControlMedicineGoods
      controlMedicineGoods: ${spring.data.solr.host}/controlMedicineGoods
      hotWords: ${spring.data.solr.host}/hotWords

# Logging configuration
logging:
  level:
    org.springframework:
      cloud: DEBUG
    com.jc519: DEBUG